version: '3.1'

services:
  app:
    command: yarn run dev
    build:
      context: frontend
      dockerfile: Dockerfile
    image: homly-node11
    ports:
      - 3000:3000
    volumes:
      #project
#      - .:/app
      - ./frontend/app:/app/app:delegated # specifically only mount the /frontend/app folder, so that node_module are still existing from the Docker Build
    extra_hosts:
      - "homly.local:172.17.0.1" # Telling the frontend how to communicate with the drupal
  web:
    build:
      context: backend
    image: homly-d8
    volumes:
      #project
      - .:/var/www/html:cached
#      - ./db/settings.local.php:/var/www/html/web/docroot/sites/default/settings.local.php:cached
      #files
      - ./web/sites/default/files:/var/www/html/web/sites/default/files:delegated
      #ssh keys
      - ~/.ssh:/root/.ssh:ro
      #control groups
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - 443:443
    links:
      - db
    restart: always

  db:
    image: mysql:5.6.35
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_volume:/var/lib/mysql
    restart: always

volumes:
  db_volume: {}
